services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/code/
    ports:
      - "3000:3000"
    command: bash -c "rm -rf /code/tmp/pids/server.pid &&
                      rails s -p 3000 -b '0.0.0.0'"